import { chromium } from 'playwright'
const BASE='http://localhost:3000'
const PASS='Password123!'
async function login(p,e){
  await p.goto(BASE+'/login',{waitUntil:'domcontentloaded'})
  await p.fill('input[type="email"]',e)
  await p.fill('input[type="password"]',PASS)
  await p.click('button[type="submit"]')
  await p.waitForURL('**/dashboard',{timeout:25000})
  await p.waitForTimeout(1200)
}
const b=await chromium.launch()
let c=await b.newContext()
let p=await c.newPage()
await login(p,'taskmanager@csm.app')
await p.goto(BASE+'/kanban',{waitUntil:'domcontentloaded'})
await p.waitForTimeout(1500)
console.log('KANBAN Drag and drop text:', (await p.textContent('body')).includes('Drag and drop')?'YES':'NO')
console.log('draggable count:', await p.locator('[draggable="true"]').count())
console.log('columns:', await p.locator('[data-testid^="kanban-column-"]').count())
console.log('cards with data-testid:', await p.locator('[data-testid^="kanban-card-"]').count())
console.log('grip icons:', await p.locator('svg.lucide-grip-vertical').count())
console.log('Move fallback:', await p.locator('button:has-text("Move")').count())
await c.close()
c=await b.newContext()
p=await c.newPage()
await login(p,'media@csm.app')
await p.goto(BASE+'/media',{waitUntil:'domcontentloaded'})
await p.waitForTimeout(1000)
console.log('MEDIA project select:', await p.locator('[data-testid="media-project-select"]').count())
console.log('MEDIA dropzone:', await p.locator('[data-testid="media-dropzone"]').count())
console.log('MEDIA has Project required:', (await p.textContent('body')).includes('Project required')?'YES':'NO')
console.log('MEDIA options:', await p.locator('[data-testid="media-project-select"] option').count())
await b.close()
