export type {
  Role,
  Permission,
  User,
  UserStatus,
} from './auth'

import type { Role, Permission } from './auth'

export const ROLES: Role[] = [
  'MARKETING',
  'ADMIN',
  'TASK_MANAGEMENT',
  'CONTENT_TEAM',
  'MEDIA_TEAM',
  'CLIENT',
]

export const PERMISSIONS: Permission[] = [
  'CLIENT_CREATE',
  'CLIENT_VIEW',
  'CLIENT_APPROVE',
  'CLIENT_REJECT',
  'CLIENT_SUBMIT',
  'PROJECT_VIEW',
  'PROJECT_APPROVE',
  'PROJECT_PUBLISH',
  'PRODUCT_CREATE',
  'PRODUCT_VIEW',
  'PRODUCT_EDIT',
  'TASK_CREATE',
  'TASK_ASSIGN',
  'TASK_VIEW',
  'TASK_UPDATE',
  'CONTENT_CREATE',
  'CONTENT_EDIT',
  'CONTENT_SUBMIT',
  'CONTENT_APPROVE',
  'CONTENT_VIEW',
  'MEDIA_UPLOAD',
  'MEDIA_EDIT',
  'MEDIA_APPROVE',
  'MEDIA_VIEW',
  'PAYMENT_VIEW',
  'PAYMENT_UPDATE',
  'USER_CREATE',
  'USER_UPDATE',
  'USER_DISABLE',
  'USER_VIEW',
  'NOTIFICATION_VIEW',
  'COMMENT_CREATE',
  'AUDIT_VIEW',
  'ROLE_MANAGE',
]
