export const CLIENT_STATUS_OPTIONS = [
  'DRAFT',
  'PENDING_ADMIN_APPROVAL',
  'REJECTED',
  'APPROVED',
] as const

export const PROJECT_STATUS_OPTIONS = [
  'DRAFT',
  'ACTIVE',
  'READY_TO_PUBLISH',
  'PUBLISHED',
  'CANCELLED',
] as const

export const TASK_STATUS_OPTIONS = [
  'TODO',
  'IN_PROGRESS',
  'BLOCKED',
  'IN_REVIEW',
  'COMPLETED',
  'CANCELLED',
] as const

export const TASK_PRIORITY_OPTIONS = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'] as const

export const TASK_TYPE_OPTIONS = ['CONTENT', 'MEDIA', 'DESIGN', 'COPYWRITING', 'SEO', 'SOCIAL', 'OTHER'] as const

export const CONTENT_STATUS_OPTIONS = [
  'DRAFT',
  'SUBMITTED',
  'UNDER_REVIEW',
  'REVISION_REQUIRED',
  'RESUBMITTED',
  'APPROVED',
] as const

export const MEDIA_STATUS_OPTIONS = [
  'PENDING',
  'UPLOADING',
  'PROCESSING',
  'READY_FOR_REVIEW',
  'REVISION_REQUIRED',
  'RESUBMITTED',
  'APPROVED',
  'FAILED',
] as const

export const PAYMENT_STATUS_OPTIONS = [
  'UNPAID',
  'PARTIALLY_PAID',
  'PAID',
  'OVERDUE',
] as const

export const REVISION_STATUS_OPTIONS = ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'] as const

export const APPROVAL_STATUS_OPTIONS = ['PENDING', 'APPROVED', 'REJECTED', 'REVISION_REQUIRED'] as const

export const ENTITY_TYPES = ['CLIENT', 'PROJECT', 'PRODUCT', 'TASK', 'CONTENT', 'MEDIA'] as const

export const ROLE_OPTIONS = [
  'MARKETING',
  'ADMIN',
  'TASK_MANAGEMENT',
  'CONTENT_TEAM',
  'MEDIA_TEAM',
  'CLIENT',
] as const

export const USER_STATUS_OPTIONS = ['ACTIVE', 'INACTIVE', 'SUSPENDED', 'LOCKED'] as const
